#app:
#  host: ec2-3-101-65-24.us-west-1.compute.amazonaws.com
#  port: 5000
#coordination:
#  host: ec2-13-52-220-237.us-west-1.compute.amazonaws.com
#  port: 9000
#lock_manager:
#  host: ec2-54-153-119-230.us-west-1.compute.amazonaws.com
#  port: 9001
#socket_ping:
#  host: ec2-3-101-65-24.us-west-1.compute.amazonaws.com
#  port: 9002

app:
  host: localhost
  port: 5000
coordination:
  host: localhost
  port: 9000
lock_manager:
  host: localhost
  port: 9001
socket_ping:
  host: localhost
  port: 9002