#app:
#  host: ec2-50-18-77-183.us-west-1.compute.amazonaws.com
#  port: 5000
#coordination:
#  host: ec2-54-219-175-140.us-west-1.compute.amazonaws.com
#  port: 9000
#lock_manager:
#  host: ec2-54-183-251-154.us-west-1.compute.amazonaws.com
#  port: 9001
#socket_ping:
#  host: ec2-50-18-77-183.us-west-1.compute.amazonaws.com
#  port: 9002

app:
  host: localhost
  port: 5000
coordination:
    host: localhost
    port: 9000
lock_manager:
    host: localhost
    port: 9001
socket_ping:
    host: localhost
    port: 9002

